import 'package:flutter/material.dart';import 'package:hire_help_ff/core/app_export.dart';import 'package:hire_help_ff/presentation/homepage_page/homepage_page.dart';import 'package:hire_help_ff/widgets/app_bar/appbar_image.dart';import 'package:hire_help_ff/widgets/app_bar/custom_app_bar.dart';import 'package:hire_help_ff/widgets/custom_bottom_bar.dart';import 'package:hire_help_ff/widgets/custom_button.dart';
// ignore_for_file: must_be_immutable
class SubscribedServicesScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, body: Container(width: getHorizontalSize(364), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: double.maxFinite, child: Container(padding: getPadding(top: 1, bottom: 1), decoration: AppDecoration.fillWhiteA700, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CustomAppBar(height: getVerticalSize(70), leadingWidth: 58, leading: AppbarImage(height: getSize(32), width: getSize(32), imagePath: ImageConstant.imgImage4, margin: getMargin(left: 26, top: 25, bottom: 11), onTap: () {onTapImagefour8(context);}), centerTitle: true, title: AppbarImage(height: getVerticalSize(69), width: getHorizontalSize(178), imagePath: ImageConstant.imgHirehelp1137x254), actions: [AppbarImage(height: getVerticalSize(32), width: getHorizontalSize(27), imagePath: ImageConstant.imgImage232x27, margin: getMargin(left: 27, top: 26, right: 27, bottom: 10))]), Padding(padding: getPadding(top: 6), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: ColorConstant.black900, endIndent: getHorizontalSize(5)))]))), Container(height: getVerticalSize(633), width: getHorizontalSize(364), padding: getPadding(left: 11, top: 31, right: 11, bottom: 31), child: Stack(alignment: Alignment.topLeft, children: [CustomButton(width: getHorizontalSize(304), text: "Subscribe to a service", margin: getMargin(top: 73), padding: ButtonPadding.PaddingT9, fontStyle: ButtonFontStyle.LatoMedium16, suffixWidget: Container(margin: getMargin(left: 30), child: CustomImageView(svgPath: ImageConstant.imgPlus)), onTap: () {onTapSubscribetoa(context);}, alignment: Alignment.topCenter), Align(alignment: Alignment.topLeft, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgImage1, height: getVerticalSize(24), width: getHorizontalSize(28), margin: getMargin(top: 6, bottom: 2)), Padding(padding: getPadding(left: 31), child: Text("Subscribed Services", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium22))]))]))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homepagePage; case BottomBarEnum.Profile: return "/"; case BottomBarEnum.Services: return "/"; case BottomBarEnum.Messages: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homepagePage: return HomepagePage(); default: return DefaultWidget();} } 
onTapImagefour8(BuildContext context) { Navigator.pushNamed(context, AppRoutes.menuScreen); } 
onTapSubscribetoa(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homepageContainerScreen); } 
 }
